[package]
name = "xml-lib"
version = "0.0.1"
edition = "2021"
description = "Rust XML Library"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
